### PR TITLE
move rxjs to peerDependency and update to ^6.2.1

### LINKED ISSUE #2: possibly need rxjs as peerDependency
same issue as https://github.com/aurelia/store/issues/25

### PR DESCRIPTION
**Pull request by doktordirk**
tried and worked for me

closes #2

### CODE REVIEW

**Comment by zewa666** [comment]
Thanks for the PR. I'm in vacation till the end of June so this will take some time to get merged.

**Review by zewa666 — COMMENTED** [review]
I'm not even sure all of these dependencies are needed as they were defined by the boilerplate i've used. I'll definitely check this when back home

**Comment by doktordirk** [comment]
dunno about requirejs and jspm builds. needs checking

**Comment by zewa666** [comment]
@doktordirk thanks again for the contribution, I'm sorry but didn't add the PR because I was doing it with one larger cleanup commit

**Pull request closed without merging**
